"""initial_full_schema

Revision ID: 361d6e7585d0
Revises: 
Create Date: 2026-05-26 11:28:26.687333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361d6e7585d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('application_media', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('application_media', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('application_media', sa.Column('upload_status', sa.String(), nullable=True))
    op.alter_column('application_media', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('application_media', 'file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('application_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_application_media_application_id'), 'application_media', ['application_id'], unique=False)
    op.alter_column('application_tags', 'applied_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_application_tags_application_id'), 'application_tags', ['application_id'], unique=False)
    op.add_column('applications', sa.Column('consent_given', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.execute("UPDATE applications SET consent_given = false WHERE consent_given IS NULL")
    op.alter_column('applications', 'consent_given', nullable=False)
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('applications', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_casting_call_id'), 'applications', ['casting_call_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.alter_column('casting_calls', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('casting_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('casting_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_casting_calls_owner_id'), 'casting_calls', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casting_calls_owner_id'), table_name='casting_calls')
    op.alter_column('casting_calls', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('casting_calls', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('casting_calls', 'deadline',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_casting_call_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.alter_column('applications', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'consent_given')
    op.drop_index(op.f('ix_application_tags_application_id'), table_name='application_tags')
    op.alter_column('application_tags', 'applied_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_application_media_application_id'), table_name='application_media')
    op.alter_column('application_media', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_media', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('application_media', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('application_media', 'upload_status')
    op.drop_column('application_media', 'thumbnail_url')
    op.drop_column('application_media', 'storage_path')
    op.alter_column('applicants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
