"""add_slug_fields_to_casting_calls

Revision ID: 9463f548c72f
Revises: c3a9f1d2e456
Create Date: 2026-05-26 18:17:14.065268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9463f548c72f'
down_revision: Union[str, None] = 'c3a9f1d2e456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_id', table_name='user_roles')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.add_column('casting_calls', sa.Column('show_slug', sa.String(), nullable=True))
    op.add_column('casting_calls', sa.Column('role_slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_casting_calls_role_slug'), 'casting_calls', ['role_slug'], unique=False)
    op.create_index(op.f('ix_casting_calls_show_slug'), 'casting_calls', ['show_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casting_calls_show_slug'), table_name='casting_calls')
    op.drop_index(op.f('ix_casting_calls_role_slug'), table_name='casting_calls')
    op.drop_column('casting_calls', 'role_slug')
    op.drop_column('casting_calls', 'show_slug')
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey')
    )
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=True)
    op.create_index('ix_user_roles_id', 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###
