"""new_tables_pitch_decks_notifications_otp

Revision ID: b80abde96bbd
Revises: 361d6e7585d0
Create Date: 2026-05-26 11:31:00.260073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80abde96bbd'
down_revision: Union[str, None] = '361d6e7585d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
