"""add_composite_indexes_for_performance

Revision ID: dad9e544fc68
Revises: f1a2b3c4d5e6
Create Date: 2026-05-29 12:52:23.632622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad9e544fc68'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_casting_call_complete', 'applications', ['casting_call_id', 'is_complete'], unique=False)
    op.create_index('ix_applications_casting_call_status', 'applications', ['casting_call_id', 'status'], unique=False)
    op.create_index('ix_applications_status_complete', 'applications', ['status', 'is_complete'], unique=False)
    op.create_index('ix_in_app_notifications_user_read', 'in_app_notifications', ['user_id', 'read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_in_app_notifications_user_read', table_name='in_app_notifications')
    op.drop_index('ix_applications_status_complete', table_name='applications')
    op.drop_index('ix_applications_casting_call_status', table_name='applications')
    op.drop_index('ix_applications_casting_call_complete', table_name='applications')
    # ### end Alembic commands ###
