"""add_is_complete_to_applications

Revision ID: e99ec8fed0f4
Revises: 9463f548c72f
Create Date: 2026-05-27 12:35:41.081998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99ec8fed0f4'
down_revision: Union[str, None] = '9463f548c72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_complete', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_applications_is_complete'), 'applications', ['is_complete'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_is_complete'), table_name='applications')
    op.drop_column('applications', 'is_complete')
    # ### end Alembic commands ###
